/**
 * YouTube Transcript Service
 * Fetches existing captions/transcripts from YouTube videos
 * Preferred over STT when available (faster, cheaper, more accurate)
 */
import { YoutubeTranscript } from 'youtube-transcript';
import { createComponentLogger } from '@main/utils/logger';

const logger = createComponentLogger('YouTubeTranscriptService');

export interface TranscriptSegment {
  text: string;
  start: number; // seconds
  duration: number; // seconds
  offset: number; // milliseconds (for compatibility)
}

export interface TranscriptAvailability {
  available: boolean;
  languages: string[]; // Available transcript languages
  hasAutoGenerated: boolean;
  hasManual: boolean;
}

export class YouTubeTranscriptService {
  /**
   * Check if transcripts are available for a video
   */
  async checkAvailability(videoUrl: string): Promise<TranscriptAvailability> {
    try {
      const videoId = this.extractVideoId(videoUrl);

      logger.info({ videoId }, 'Checking transcript availability');

      // Try to fetch transcripts in different languages
      const languages = ['en', 'fr', 'es', 'de', 'it', 'pt', 'ja', 'ko', 'zh'];
      const availableLanguages: string[] = [];
      let hasAutoGenerated = false;
      let hasManual = false;

      for (const lang of languages) {
        try {
          const transcripts = await YoutubeTranscript.fetchTranscript(videoId, {
            lang,
          });

          if (transcripts && transcripts.length > 0) {
            availableLanguages.push(lang);

            // Check if it's auto-generated (heuristic: check metadata if available)
            // youtube-transcript doesn't provide this info directly, so we assume
            // that if we successfully fetched it, it exists
            hasAutoGenerated = true;
          }
        } catch (error) {
          // Transcript not available for this language
          continue;
        }
      }

      const available = availableLanguages.length > 0;

      logger.info({
        videoId,
        available,
        languages: availableLanguages,
      }, 'Transcript availability checked');

      return {
        available,
        languages: availableLanguages,
        hasAutoGenerated,
        hasManual: false, // We can't distinguish without additional API access
      };
    } catch (error) {
      logger.error({ err: error, videoUrl }, 'Failed to check transcript availability');
      return {
        available: false,
        languages: [],
        hasAutoGenerated: false,
        hasManual: false,
      };
    }
  }

  /**
   * Fetch transcript for a video
   */
  async fetchTranscript(
    videoUrl: string,
    language?: string
  ): Promise<TranscriptSegment[]> {
    try {
      const videoId = this.extractVideoId(videoUrl);

      logger.info({ videoId, language }, 'Fetching transcript');

      const options = language ? { lang: language } : {};
      const rawTranscript = await YoutubeTranscript.fetchTranscript(videoId, options);

      // Convert to our format
      const segments: TranscriptSegment[] = rawTranscript.map((segment) => ({
        text: segment.text,
        start: segment.offset / 1000, // Convert ms to seconds
        duration: segment.duration / 1000, // Convert ms to seconds
        offset: segment.offset, // Keep original ms offset
      }));

      logger.info({
        videoId,
        language,
        segmentCount: segments.length,
        totalDuration: segments.reduce((sum, s) => sum + s.duration, 0),
      }, 'Transcript fetched successfully');

      return segments;
    } catch (error) {
      logger.error({ err: error, videoUrl, language }, 'Failed to fetch transcript');
      throw new Error(`Failed to fetch transcript: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Extract video ID from YouTube URL
   */
  private extractVideoId(url: string): string {
    // Handle various YouTube URL formats
    const patterns = [
      /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
      /^([a-zA-Z0-9_-]{11})$/, // Direct video ID
    ];

    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match) {
        return match[1];
      }
    }

    throw new Error(`Invalid YouTube URL: ${url}`);
  }

  /**
   * Get the best available language for transcripts
   * Prioritizes: exact match > language family match > fallback to first available
   */
  async getBestLanguage(
    videoUrl: string,
    preferredLanguage: string
  ): Promise<string | null> {
    try {
      const availability = await this.checkAvailability(videoUrl);

      if (!availability.available) {
        return null;
      }

      const { languages } = availability;

      // Extract base language code (e.g., 'en-US' -> 'en')
      const basePreferred = preferredLanguage.split('-')[0].toLowerCase();

      // 1. Try exact match
      if (languages.includes(preferredLanguage)) {
        return preferredLanguage;
      }

      // 2. Try base language match
      if (languages.includes(basePreferred)) {
        return basePreferred;
      }

      // 3. Try to find any language from the same family
      const familyMatch = languages.find((lang) => lang.startsWith(basePreferred));
      if (familyMatch) {
        return familyMatch;
      }

      // 4. Fallback to first available language
      logger.warn({
        preferredLanguage,
        availableLanguages: languages,
      }, 'Preferred language not available, using fallback');

      return languages[0];
    } catch (error) {
      logger.error({ err: error, videoUrl, preferredLanguage }, 'Failed to get best language');
      return null;
    }
  }

  /**
   * Estimate cost savings by using transcripts instead of STT
   * Based on video duration and STT pricing
   */
  estimateCostSavings(durationSeconds: number, sttProvider: 'google' | 'azure'): {
    sttCost: number;
    transcriptCost: number;
    savings: number;
    savingsPercent: number;
  } {
    const durationMinutes = durationSeconds / 60;

    // STT costs per minute
    const sttCostPerMinute = sttProvider === 'azure' ? 0.00096 : 0.0024;

    // Transcript is free!
    const transcriptCost = 0;
    const sttCost = durationMinutes * sttCostPerMinute;
    const savings = sttCost;
    const savingsPercent = 100;

    return {
      sttCost: parseFloat(sttCost.toFixed(4)),
      transcriptCost,
      savings: parseFloat(savings.toFixed(4)),
      savingsPercent,
    };
  }
}

// Singleton instance
let instance: YouTubeTranscriptService | null = null;

export function getYouTubeTranscriptService(): YouTubeTranscriptService {
  if (!instance) {
    instance = new YouTubeTranscriptService();
  }
  return instance;
}
