/**
 * Test script for YouTube transcript functionality
 * Tests transcript detection and fetching
 */
import 'dotenv/config';
import { getYouTubeTranscriptService } from '../src/main/services/youtube-transcript-service';

async function testYouTubeTranscript() {
  console.log('🎥 Testing YouTube Transcript Service\n');

  const transcriptService = getYouTubeTranscriptService();

  // Test with a known video that has transcripts
  // Using a popular tech talk video as example
  const testVideos = [
    {
      name: 'Test Video 1 (Tech Talk)',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Replace with actual video
      description: 'Popular video likely to have transcripts',
    },
    {
      name: 'Test Video 2 (Tutorial)',
      url: 'https://www.youtube.com/watch?v=9bZkp7q19f0', // PSY - GANGNAM STYLE (has multiple language transcripts)
      description: 'Music video with multiple language transcripts',
    },
  ];

  for (const video of testVideos) {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`📺 ${video.name}`);
    console.log(`   ${video.description}`);
    console.log(`   URL: ${video.url}`);
    console.log(`${'='.repeat(60)}\n`);

    try {
      // Check availability
      console.log('🔍 Checking transcript availability...');
      const availability = await transcriptService.checkAvailability(video.url);

      if (!availability.available) {
        console.log('❌ No transcripts available for this video\n');
        continue;
      }

      console.log('✅ Transcripts available!');
      console.log(`   Languages: ${availability.languages.join(', ')}`);
      console.log(`   Auto-generated: ${availability.hasAutoGenerated ? 'Yes' : 'No'}`);
      console.log(`   Manual: ${availability.hasManual ? 'Yes' : 'No'}\n`);

      // Test best language selection
      const preferredLanguages = ['en', 'fr', 'es'];

      for (const prefLang of preferredLanguages) {
        console.log(`🌐 Finding best match for preferred language: ${prefLang}`);
        const bestLang = await transcriptService.getBestLanguage(video.url, prefLang);

        if (bestLang) {
          console.log(`   ✓ Best match: ${bestLang}`);
        } else {
          console.log(`   ✗ No match found`);
        }
      }

      // Fetch transcript in first available language
      console.log(`\n📄 Fetching transcript in ${availability.languages[0]}...`);
      const transcript = await transcriptService.fetchTranscript(
        video.url,
        availability.languages[0]
      );

      console.log(`   ✅ Fetched ${transcript.length} segments`);

      if (transcript.length > 0) {
        const totalDuration = transcript.reduce((sum, s) => sum + s.duration, 0);
        console.log(`   Total duration: ${(totalDuration / 60).toFixed(2)} minutes`);

        // Show first 3 segments as preview
        console.log('\n   📝 Preview (first 3 segments):');
        transcript.slice(0, 3).forEach((segment, i) => {
          const timestamp = new Date(segment.start * 1000).toISOString().substr(11, 8);
          console.log(`      [${timestamp}] ${segment.text.substring(0, 80)}${segment.text.length > 80 ? '...' : ''}`);
        });

        // Calculate cost savings
        console.log('\n   💰 Cost Savings Estimate:');
        const azureSavings = transcriptService.estimateCostSavings(totalDuration, 'azure');
        const googleSavings = transcriptService.estimateCostSavings(totalDuration, 'google');

        console.log(`      Azure STT cost: $${azureSavings.sttCost.toFixed(4)}`);
        console.log(`      Google STT cost: $${googleSavings.sttCost.toFixed(4)}`);
        console.log(`      Transcript cost: $0.00 (FREE)`);
        console.log(`      💸 Savings with Azure: $${azureSavings.savings.toFixed(4)} (${azureSavings.savingsPercent}%)`);
        console.log(`      💸 Savings with Google: $${googleSavings.savings.toFixed(4)} (${googleSavings.savingsPercent}%)`);
      }

    } catch (error) {
      console.error(`❌ Error testing video: ${error}`);
    }
  }

  console.log(`\n${'='.repeat(60)}`);
  console.log('✅ YouTube Transcript Service Test Complete');
  console.log(`${'='.repeat(60)}\n`);

  console.log('💡 Key Benefits of Using Transcripts:');
  console.log('   • 100% cost savings on STT');
  console.log('   • Faster processing (no audio transcription needed)');
  console.log('   • Often more accurate than STT');
  console.log('   • Works for videos without audio');
  console.log('   • Supports multiple languages when available\n');

  console.log('📋 Next Steps:');
  console.log('   1. Add transcript detection to main pipeline');
  console.log('   2. Add UI toggle to prefer transcripts over STT');
  console.log('   3. Show transcript availability status in UI');
  console.log('   4. Allow users to select transcript language\n');
}

// Run test
testYouTubeTranscript()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
