/**
 * Pipeline and audio processing types
 */

export type PipelineStatus = 'idle' | 'starting' | 'running' | 'paused' | 'stopping' | 'error';

export interface PipelineConfig {
  youtubeUrl: string;
  sttLanguage: string;
  targetLanguage: string;
  targetLatency: number;
  audioChunkDuration: number;
  // Transcript preferences
  preferTranscriptOverSTT?: boolean; // Default: true (use transcript when available)
  transcriptLanguage?: string; // Preferred transcript language (auto-detected if not specified)
}

export interface LatencyMetrics {
  total: number;
  capture: number;
  stt: number;
  translation: number;
  tts: number;
  output: number;
  timestamp: number;
}

export interface PipelineEvent {
  type: 'status' | 'latency' | 'transcript' | 'translation' | 'error' | 'transcript-available';
  timestamp: number;
  data: unknown;
}

export interface TranscriptAvailableEvent {
  available: boolean;
  languages: string[];
  hasAutoGenerated: boolean;
  hasManual: boolean;
  estimatedSavings?: {
    sttCost: number;
    transcriptCost: number;
    savings: number;
    savingsPercent: number;
  };
}

export interface AudioChunk {
  data: Buffer;
  timestamp: number;
  sequence: number;
}
